import type { Project } from "./model";

export const projects: Project[] = [
  { title: "Happy", description: "Mostra localização de orfanatos próximos abertos para visitação.", detailedDescription: "Happy mostra localização de orfanatos próximos abertos para visitação. Leve alegria e esperança para crianças em adoção.", imageSrc: "/Happy.webp", githubLink: "https://github.com/kristyancarvalho/Happy", platforms: ["web", "mobile"], technologies: [{ name: "React", logo: "/tech-logos/react.webp" }, { name: "TypeScript", logo: "/tech-logos/typescript.webp" }, { name: "Node.js", logo: "/tech-logos/Node.js.webp" }, { name: "Express", logo: "/tech-logos/Express.webp" }, { name: "SQLite", logo: "/tech-logos/SQLite.webp" }, { name: "Expo", logo: "/tech-logos/Expo.webp" }, { name: "React Native", logo: "/tech-logos/react-native.webp" }, { name: "Jest", logo: "/tech-logos/Jest.webp" }] },
  { title: "EcoCash", description: "Plataforma sustentável que conecta hardware, web e mobile para incentivar a reciclagem.", detailedDescription: "Plataforma digital sustentável que conecta hardware e web para incentivar a reciclagem. Utilizando Arduino, ESP8266 e React, o Ecocash coleta dados de materiais recicláveis e os exibe em tempo real.", imageSrc: "/EcoCash.webp", githubLink: "https://github.com/kristyancarvalho/EcoCash", platforms: ["web", "mobile"], technologies: [{ name: "TypeScript", logo: "/tech-logos/typescript.webp" }, { name: "React", logo: "/tech-logos/react.webp" }, { name: "Vite", logo: "/tech-logos/vite.webp" }, { name: "Firebase", logo: "/tech-logos/Firebase.webp" }] },
  { title: "Nearby", description: "Aplicativo mobile de clube de benefícios com cupons em estabelecimentos próximos.", detailedDescription: "Aplicativo mobile inovador que conecta você a um clube de benefícios exclusivo com cupons e descontos em estabelecimentos próximos.", imageSrc: "/Nearby.webp", githubLink: "https://github.com/kristyancarvalho/Nearby", platforms: ["mobile"], technologies: [{ name: "TypeScript", logo: "/tech-logos/typescript.webp" }, { name: "React Native", logo: "/tech-logos/react-native.webp" }, { name: "Expo", logo: "/tech-logos/Expo.webp" }, { name: "Node.js", logo: "/tech-logos/Node.js.webp" }, { name: "Express", logo: "/tech-logos/Express.webp" }, { name: "SQLite", logo: "/tech-logos/SQLite.webp" }, { name: "Prisma", logo: "/tech-logos/Prisma.webp" }] },
  { title: "Tux Letter", description: "Newsletter automatizada com as principais notícias sobre Linux e open source.", detailedDescription: "Sistema de newsletter automatizada que coleta, filtra e envia diariamente as principais notícias sobre Linux e software open source.", imageSrc: "/TuxLetter.webp", githubLink: "https://github.com/kristyancarvalho/tux-letter", platforms: ["cli"], technologies: [{ name: "TypeScript", logo: "/tech-logos/typescript.webp" }, { name: "Node.js", logo: "/tech-logos/Node.js.webp" }] },
  { title: "OpenPilot.nvim", description: "Agente de código inteligente para o Neovim, inspirado no GitHub Copilot.", detailedDescription: "Agente de código inteligente para o editor Neovim. Suporte a múltiplos modelos de IA, controle de rate limit e configuração personalizada.", imageSrc: "/OpenPilot.webp", githubLink: "https://github.com/kristyancarvalho/openpilot.nvim", platforms: ["cli"], technologies: [{ name: "Go", logo: "/tech-logos/go.svg" }, { name: "Lua", logo: "/tech-logos/lua.svg" }] },
  { title: "GitPulse", description: "API que gera badges SVG com o último projeto ativo de um usuário no GitHub.", detailedDescription: "API que gera badges em SVG com o último projeto ativo de um usuário no GitHub, ideal para READMEs e portfólios.", imageSrc: "/GitPulse.webp", githubLink: "https://github.com/kristyancarvalho/gitpulse", platforms: ["web"], technologies: [{ name: "Go", logo: "/tech-logos/go.svg" }] },
  { title: "Codewhisper CLI", description: "Agente de código via linha de comando para auxiliar desenvolvedores.", detailedDescription: "Ferramenta de linha de comando que utiliza a API do OpenRouter para fornecer respostas baseadas no contexto de arquivos de código fornecidos.", imageSrc: "/Codewhisper.webp", githubLink: "https://github.com/kristyancarvalho/codewhisper-cli", platforms: ["cli"], technologies: [{ name: "TypeScript", logo: "/tech-logos/typescript.webp" }, { name: "Node.js", logo: "/tech-logos/Node.js.webp" }, { name: "SQLite", logo: "/tech-logos/SQLite.webp" }] },
  { title: "Gerenciador do Blog", description: "Programa desktop para gerenciar a aba Posts deste site.", detailedDescription: "Programa desktop para gerenciar a aba Posts deste site, construído com Electron e Firebase.", imageSrc: "/BlogManager.webp", githubLink: "https://github.com/kristyancarvalho/blog-manager-app", platforms: ["desktop"], technologies: [{ name: "TypeScript", logo: "/tech-logos/typescript.webp" }, { name: "React", logo: "/tech-logos/react.webp" }, { name: "Vite", logo: "/tech-logos/vite.webp" }, { name: "Electron", logo: "/tech-logos/Electron.webp" }, { name: "Firebase", logo: "/tech-logos/Firebase.webp" }] },
  { title: "Paint", description: "Programa desktop para desenhar em ElectronJS, ReactJS e MaterialUI.", detailedDescription: "App para desenhar desenvolvido em ElectronJS, ReactJS e MaterialUI.", imageSrc: "/Paint.webp", githubLink: "https://github.com/kristyancarvalho/paint-desktop-app", platforms: ["desktop"], technologies: [{ name: "React", logo: "/tech-logos/react.webp" }, { name: "JavaScript", logo: "/tech-logos/javascript.webp" }, { name: "Electron", logo: "/tech-logos/Electron.webp" }, { name: "Node.js", logo: "/tech-logos/Node.js.webp" }, { name: "Webpack", logo: "/tech-logos/Webpack.webp" }, { name: "Material UI", logo: "/tech-logos/Material UI.webp" }] },
  { title: "Salotti Run", description: "Jogo runner endless para culminância de 2023.", detailedDescription: "Jogo do gênero runner endless desenvolvido com JavaScript, HTML e CSS para projeto de culminância em 2023.", imageSrc: "/SalottiRun.webp", githubLink: "https://github.com/kristyancarvalho/salotti-run-game", platforms: ["web"], technologies: [{ name: "HTML5", logo: "/tech-logos/html5.webp" }, { name: "CSS3", logo: "/tech-logos/css.webp" }, { name: "JavaScript", logo: "/tech-logos/javascript.webp" }] },
  { title: "LetMeAsk", description: "Crie salas para responder ou fazer perguntas ao vivo durante uma live.", detailedDescription: "Crie salas interativas para responder ou fazer perguntas ao vivo durante uma live.", imageSrc: "/Letmeask.webp", githubLink: "https://github.com/kristyancarvalho/Letmeask", platforms: ["web"], technologies: [{ name: "React", logo: "/tech-logos/react.webp" }, { name: "TypeScript", logo: "/tech-logos/typescript.webp" }, { name: "Firebase", logo: "/tech-logos/Firebase.webp" }, { name: "Sass", logo: "/tech-logos/Sass.webp" }, { name: "Jest", logo: "/tech-logos/Jest.webp" }] },
  { title: "MoveIt", description: "Temporizador pomodoro gamificado. Desenvolvido em NextJS durante o NLW 4.", detailedDescription: "Temporizador pomodoro gamificado desenvolvido em NextJS e TypeScript durante o NLW 4 da Rocketseat.", imageSrc: "/MoveIt.webp", githubLink: "https://github.com/kristyancarvalho/MoveIt", platforms: ["web"], technologies: [{ name: "Next.js", logo: "/tech-logos/nextjs.webp" }, { name: "TypeScript", logo: "/tech-logos/typescript.webp" }] },
  { title: "Plann.er API", description: "API de planejamento de viagem. NLW Journey 2024.", detailedDescription: "API do Plann.er, aplicação desenvolvida durante o bootcamp NLW Journey da Rocketseat.", imageSrc: "/Planner.webp", githubLink: "https://github.com/kristyancarvalho/plann.er-backend", platforms: ["web"], technologies: [{ name: "Fastify", logo: "/tech-logos/Fastify.webp" }, { name: "TypeScript", logo: "/tech-logos/typescript.webp" }, { name: "Prisma", logo: "/tech-logos/Prisma.webp" }] },
  { title: "Paralelismo", description: "Benchmark entre processamento de imagens em single thread e Worker Threads.", detailedDescription: "Benchmark comparativo entre single thread e Worker Threads em Node.js para processamento de imagens.", imageSrc: "/Benchmark.webp", githubLink: "https://github.com/kristyancarvalho/multi-thread-image-processing", platforms: ["cli"], technologies: [{ name: "Node.js", logo: "/tech-logos/Node.js.webp" }, { name: "JavaScript", logo: "/tech-logos/javascript.webp" }, { name: "Express", logo: "/tech-logos/Express.webp" }] },
  { title: "C# Snake", description: "Jogo da cobrinha que roda no terminal, feito para aprender C#.", detailedDescription: "Jogo da cobrinha que roda no terminal. Projeto didático desenvolvido enquanto aprendia C#.", imageSrc: "/SnakeGame.webp", githubLink: "https://github.com/kristyancarvalho/terminal-snake-game", platforms: ["cli"], technologies: [{ name: "C#", logo: "/tech-logos/CSharp.webp" }] },
];
